name: Test Comment on Gist

on:
  workflow_dispatch:
    inputs:
      gist_id:
        description: 'Gist ID to comment on'
        required: true
        type: string
      file_path:
        description: 'Path to file to use as comment'
        required: true
        type: string

jobs:
  comment-file:
    uses: serpuniversity/.github/.github/workflows/comment-on-gist.yml@main
    with:
      gist_id: ${{ github.event.inputs.gist_id }}
      content_source: "file"
      file_path: ${{ github.event.inputs.file_path }}
      comment_prefix: "📝 Update from repository"
    secrets:
      GH_PAT_PROFESSOR_SERP: ${{ secrets.GH_PAT_PROFESSOR_SERP }}